### ISSUE TITLE
It does not work !

### ISSUE THREAD

**Issue by Ayasticall** [Masihdeveloper/Boost-Unboost-Announcer#4]
hello, I did everything correctly, it puts me in the terminal "Successfully logged in as ????#4659" but nothing happens

**Comment by Masihdeveloper** [comment]
Hello @Ayasticall

Thank you for getting in touch. You've followed all the steps correctly, and your question is appreciated. To activate the [related 
features](https://github.com/Masihdeveloper/Boost-Unboost-Announcer#-preview-images), a member must first **boost** or **unboost** your server, at which point the bot will execute the necessary actions.

All steps have been thoroughly tested, but if you encounter any *bugs*, please let me know.

**Comment by Ayasticall** [comment]
Sorry, I didn't know you had to boost ! Thanks
